// Dynamic import for xlsx to avoid SSR issues
let XLSX: typeof import("xlsx") | null = null;

const getXLSX = async () => {
  if (!XLSX) {
    XLSX = await import("xlsx");
  }
  return XLSX;
};
import type { BaselineSpec, RequirementsPayload } from "./rules";
import type { AiSummary } from "./openrouter";

export type ExportData = {
  requirements: RequirementsPayload;
  baselineSpec?: BaselineSpec;
  aiSummary: AiSummary | null;
  generatedAt: string;
};

const formatDate = (dateString: string): string => {
  try {
    return new Date(dateString).toLocaleString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return dateString;
  }
};

const parseQuantity = (quantity: string): number => {
  if (quantity === "1") return 1;
  if (quantity === "5-20") return 12; // Average
  if (quantity === "20-50") return 35; // Average
  if (quantity === "50-200") return 125; // Average
  if (quantity === "200+") return 250; // Conservative estimate
  return 1;
};

export const exportToExcel = async (data: ExportData, filename = "hardware-quotation") => {
  const xlsx = await getXLSX();
  const workbook = xlsx.utils.book_new();

  // Sheet 1: Quotation Summary
  const summaryData = [
    ["HARDWARE CONFIGURATION QUOTATION", ""],
    ["Generated by Rain Computers", ""],
    ["Generated At", formatDate(data.generatedAt)],
    ["", ""],
    ["REQUIREMENTS", ""],
    ["Usage Type", data.requirements.usageType],
    ["Budget Range", data.requirements.budgetRange],
    ["Quantity", data.requirements.quantity],
    ["Form Factor", data.requirements.formFactor],
    ["Performance Priority", data.requirements.performancePriority],
    ["Required Software", data.requirements.requiredSoftware.join(", ")],
    ["Brand Constraints", data.requirements.brandConstraints || "None"],
    ["", ""],
  ];

  if (data.baselineSpec) {
    summaryData.push(
      ["BASELINE SPECIFICATION", ""],
      ["CPU", data.baselineSpec.cpu],
      ["GPU", data.baselineSpec.gpu],
      ["RAM", data.baselineSpec.ram],
      ["Storage", data.baselineSpec.storage],
      ["Networking", data.baselineSpec.networking],
      ["Display", data.baselineSpec.display || "N/A"],
      ["Estimated Unit Price", data.baselineSpec.estimatedUnitPrice],
      ["Recommended Vendors", data.baselineSpec.recommendedVendors.join(", ")],
      ["", ""]
    );
  }

  if (data.aiSummary) {
    summaryData.push(
      ["AI ENHANCED ANALYSIS", ""],
      ["CPU", data.aiSummary.cpu],
      ...(data.aiSummary.cpuCores ? [["  Cores/Threads", `${data.aiSummary.cpuCores}/${data.aiSummary.cpuThreads || "—"}`]] : []),
      ...(data.aiSummary.cpuCache ? [["  Cache", data.aiSummary.cpuCache]] : []),
      ...(data.aiSummary.cpuFrequency ? [["  Frequency", data.aiSummary.cpuFrequency]] : []),
      ["GPU", data.aiSummary.gpu],
      ["RAM", data.aiSummary.ram],
      ...(data.aiSummary.ramSlots ? [["  RAM Slots", data.aiSummary.ramSlots]] : []),
      ...(data.aiSummary.ramSpeed ? [["  RAM Speed", data.aiSummary.ramSpeed]] : []),
      ["Storage", data.aiSummary.storage],
      ...(data.aiSummary.nvmeSlots ? [["  NVMe Slots", data.aiSummary.nvmeSlots]] : []),
      ...(data.aiSummary.powerSupply ? [["Power Supply", data.aiSummary.powerSupply]] : []),
      ...(data.aiSummary.batteryInfo ? [["Battery", data.aiSummary.batteryInfo]] : []),
      ...(data.aiSummary.screen ? [["Display", data.aiSummary.screen]] : []),
      ...(data.aiSummary.ioPorts ? [["I/O Ports", data.aiSummary.ioPorts]] : []),
      ...(data.aiSummary.webcam ? [["Webcam", data.aiSummary.webcam]] : []),
      ...(data.aiSummary.motherboard ? [["Motherboard", data.aiSummary.motherboard]] : []),
      ...(data.aiSummary.coolingSystem ? [["Cooling System", data.aiSummary.coolingSystem]] : []),
      ...(data.aiSummary.audioFeatures ? [["Audio Features", data.aiSummary.audioFeatures]] : []),
      ...(data.aiSummary.networkFeatures ? [["Network Features", data.aiSummary.networkFeatures]] : []),
      ...(data.aiSummary.size ? [["Size", data.aiSummary.size]] : []),
      ...(data.aiSummary.weight ? [["Weight", data.aiSummary.weight]] : []),
      ...(data.aiSummary.upgradability ? [["Upgradability", data.aiSummary.upgradability]] : []),
      ...(data.aiSummary.model ? [["Model", data.aiSummary.model]] : []),
      ...(data.aiSummary.pcName ? [["PC Name", data.aiSummary.pcName]] : []),
      ["Unit Price", data.aiSummary.unitPrice],
      ["Bulk Scaling Notes", data.aiSummary.bulkScaling],
      ["", ""]
    );

    // Alternatives removed from AI summary
  }

  if (data.baselineSpec?.accessories && data.baselineSpec.accessories.length > 0) {
    summaryData.push(["", ""], ["ACCESSORIES", ""]);
    data.baselineSpec.accessories.forEach((acc) => {
      summaryData.push(["", acc]);
    });
  }

  if (data.baselineSpec?.notes && data.baselineSpec.notes.length > 0) {
    summaryData.push(["", ""], ["NOTES", ""]);
    data.baselineSpec.notes.forEach((note) => {
      summaryData.push(["", note]);
    });
  }

  const summarySheet = xlsx.utils.aoa_to_sheet(summaryData);
  xlsx.utils.book_append_sheet(workbook, summarySheet, "Quotation Summary");

  // Sheet 2: Line Items (for bulk orders)
  const quantity = parseQuantity(data.requirements.quantity);
  const lineItems = [
    ["Item", "Description", "Quantity", "Unit Price", "Total Price"],
    [
      "Hardware Configuration",
      `${data.requirements.formFactor} - ${data.requirements.usageType}`,
      quantity.toString(),
      data.aiSummary?.unitPrice || data.baselineSpec?.estimatedUnitPrice || "Price on request",
    ],
  ];

  if (data.baselineSpec?.accessories && data.baselineSpec.accessories.length > 0) {
    data.baselineSpec.accessories.forEach((acc) => {
      lineItems.push([acc, acc, quantity.toString(), "Included", "Included"]);
    });
  }

  const lineItemsSheet = xlsx.utils.aoa_to_sheet(lineItems);
  xlsx.utils.book_append_sheet(workbook, lineItemsSheet, "Line Items");

  // Set column widths
  summarySheet["!cols"] = [{ wch: 30 }, { wch: 60 }];
  lineItemsSheet["!cols"] = [{ wch: 25 }, { wch: 40 }, { wch: 12 }, { wch: 15 }, { wch: 15 }];

  // Generate file
  xlsx.writeFile(workbook, `${filename}.xlsx`);
};

export const exportToCSV = (data: ExportData, filename = "hardware-quotation") => {
  const rows: string[][] = [
    ["HARDWARE CONFIGURATION QUOTATION"],
    ["Generated by Rain Computers"],
    ["Generated At", formatDate(data.generatedAt)],
    [""],
    ["REQUIREMENTS"],
    ["Usage Type", data.requirements.usageType],
    ["Budget Range", data.requirements.budgetRange],
    ["Quantity", data.requirements.quantity],
    ["Form Factor", data.requirements.formFactor],
    ["Performance Priority", data.requirements.performancePriority],
    ["Required Software", data.requirements.requiredSoftware.join(", ")],
    ["Brand Constraints", data.requirements.brandConstraints || "None"],
    [""],
  ];

  if (data.baselineSpec) {
    rows.push(
      ["BASELINE SPECIFICATION"],
      ["CPU", data.baselineSpec.cpu],
      ["GPU", data.baselineSpec.gpu],
      ["RAM", data.baselineSpec.ram],
      ["Storage", data.baselineSpec.storage],
      ["Networking", data.baselineSpec.networking],
      ["Display", data.baselineSpec.display || "N/A"],
      ["Estimated Unit Price", data.baselineSpec.estimatedUnitPrice],
      ["Recommended Vendors", data.baselineSpec.recommendedVendors.join(", ")]
    );
  }

  if (data.aiSummary) {
    rows.push(
      [""],
      ["AI ENHANCED ANALYSIS"],
      ["CPU", data.aiSummary.cpu],
      ...(data.aiSummary.cpuCores ? [["  Cores/Threads", `${data.aiSummary.cpuCores}/${data.aiSummary.cpuThreads || "—"}`]] : []),
      ...(data.aiSummary.cpuCache ? [["  Cache", data.aiSummary.cpuCache]] : []),
      ...(data.aiSummary.cpuFrequency ? [["  Frequency", data.aiSummary.cpuFrequency]] : []),
      ["GPU", data.aiSummary.gpu],
      ["RAM", data.aiSummary.ram],
      ...(data.aiSummary.ramSlots ? [["  RAM Slots", data.aiSummary.ramSlots]] : []),
      ...(data.aiSummary.ramSpeed ? [["  RAM Speed", data.aiSummary.ramSpeed]] : []),
      ["Storage", data.aiSummary.storage],
      ...(data.aiSummary.nvmeSlots ? [["  NVMe Slots", data.aiSummary.nvmeSlots]] : []),
      ...(data.aiSummary.powerSupply ? [["Power Supply", data.aiSummary.powerSupply]] : []),
      ...(data.aiSummary.batteryInfo ? [["Battery", data.aiSummary.batteryInfo]] : []),
      ...(data.aiSummary.screen ? [["Display", data.aiSummary.screen]] : []),
      ...(data.aiSummary.ioPorts ? [["I/O Ports", data.aiSummary.ioPorts]] : []),
      ...(data.aiSummary.webcam ? [["Webcam", data.aiSummary.webcam]] : []),
      ...(data.aiSummary.motherboard ? [["Motherboard", data.aiSummary.motherboard]] : []),
      ...(data.aiSummary.coolingSystem ? [["Cooling System", data.aiSummary.coolingSystem]] : []),
      ...(data.aiSummary.audioFeatures ? [["Audio Features", data.aiSummary.audioFeatures]] : []),
      ...(data.aiSummary.networkFeatures ? [["Network Features", data.aiSummary.networkFeatures]] : []),
      ...(data.aiSummary.size ? [["Size", data.aiSummary.size]] : []),
      ...(data.aiSummary.weight ? [["Weight", data.aiSummary.weight]] : []),
      ...(data.aiSummary.upgradability ? [["Upgradability", data.aiSummary.upgradability]] : []),
      ...(data.aiSummary.model ? [["Model", data.aiSummary.model]] : []),
      ...(data.aiSummary.pcName ? [["PC Name", data.aiSummary.pcName]] : []),
      ["Unit Price", data.aiSummary.unitPrice],
      ["Bulk Scaling Notes", data.aiSummary.bulkScaling]
    );

    // Alternatives removed from AI summary
  }

  // Convert to CSV string
  const csvContent = rows
    .map((row) =>
      row
        .map((cell) => {
          const cellStr = String(cell || "");
          // Escape quotes and wrap in quotes if contains comma, quote, or newline
          if (cellStr.includes(",") || cellStr.includes('"') || cellStr.includes("\n")) {
            return `"${cellStr.replace(/"/g, '""')}"`;
          }
          return cellStr;
        })
        .join(",")
    )
    .join("\n");

  // Create blob and download
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}.csv`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

